services:
    db:
        image: mysql:8.4.4
        container_name: ${COMPOSE_PROJECT_NAME}.db.docker
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USERNAME}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
        ports:
            - 127.0.0.1:${DATABASE_PORT}:3306
        volumes:
            - db.data:/var/lib/mysql

    redis_session:
        image: redis:8.0-M03-alpine
        container_name: ${COMPOSE_PROJECT_NAME}.redis_session.docker
        restart: unless-stopped
        command: redis-server --requirepass ${REDIS_SESSION_PASS}
        ports:
            - 127.0.0.1:${REDIS_SESSION_PORT}:6379
        volumes:
            - redis_session.data:/data

    rabbitmq:
        image: rabbitmq:4.0-management
        container_name: ${COMPOSE_PROJECT_NAME}.rabbitmq.docker
        restart: unless-stopped
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        ports:
            - 127.0.0.1:${RABBITMQ_PORT}:5672
            - 127.0.0.1:${RABBITMQ_MANAGEMENT_PORT}:15672

    maildev:
        image: soulteary/maildev
        container_name: ${COMPOSE_PROJECT_NAME}.maildev.docker
        restart: unless-stopped
        ports:
            - 127.0.0.1:1080:1080
            - 127.0.0.1:1025:1025

volumes:
    db.data:
    redis_session.data:
